/**
 * Скрипт сканирования локальных шрифтов.
 *
 * Сканирует папку public/fonts/ на наличие .ttf/.otf/.woff/.woff2 файлов
 * и генерирует:
 *   src/generated/localFonts.css  — @font-face декларации
 *   src/generated/localFonts.js   — массив объектов для конструктора
 *
 * Запуск вручную:  node scripts/scan-fonts.mjs
 * Автоматически запускается Vite-плагином при добавлении/удалении шрифтов.
 *
 * Структура папки public/fonts/:
 *   public/fonts/
 *     НазваниеШрифта.ttf                     → группа «local»
 *     спортивные/НазваниеШрифта.ttf           → группа «спортивные»
 *     рукописные/НазваниеШрифта.ttf           → группа «рукописные»
 *     жирные/НазваниеШрифта-Bold.ttf          → группа «жирные»
 *
 * Именование файлов:
 *   НазваниеШрифта.ttf              → weight 400 (Regular)
 *   НазваниеШрифта-Regular.ttf      → weight 400
 *   НазваниеШрифта-Bold.ttf         → weight 700
 *   НазваниеШрифта-Light.ttf        → weight 300
 *   НазваниеШрифта-Medium.ttf       → weight 500
 *   НазваниеШрифта-SemiBold.ttf     → weight 600
 *   НазваниеШрифта-ExtraBold.ttf    → weight 800
 *   НазваниеШрифта-Black.ttf        → weight 900
 *   НазваниеШрифта-Thin.ttf         → weight 100
 *   НазваниеШрифта-Italic.ttf       → italic
 *   НазваниеШрифта-BoldItalic.ttf   → weight 700, italic
 */

import { readdirSync, writeFileSync, existsSync, mkdirSync, statSync } from "node:fs";
import { join, extname, basename, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const FONTS_DIR = join(ROOT, "public", "fonts");
const OUT_DIR = join(ROOT, "src", "generated");
const FONT_EXTENSIONS = new Set([".ttf", ".otf", ".woff", ".woff2"]);

const WEIGHT_MAP = {
  thin: 100,
  hairline: 100,
  extralight: 200,
  ultralight: 200,
  light: 300,
  regular: 400,
  normal: 400,
  medium: 500,
  semibold: 600,
  demibold: 600,
  bold: 700,
  extrabold: 800,
  ultrabold: 800,
  black: 900,
  heavy: 900,
};

const FORMAT_MAP = {
  ".ttf": "truetype",
  ".otf": "opentype",
  ".woff": "woff",
  ".woff2": "woff2",
};

function parseFontFile(filename, group, urlPath) {
  const ext = extname(filename).toLowerCase();
  if (!FONT_EXTENSIONS.has(ext)) return null;

  const name = basename(filename, extname(filename));
  const parts = name.split("-");
  const family = parts[0].replace(/([a-z])([A-Z])/g, "$1 $2");

  let weight = 400;
  let italic = false;

  if (parts.length > 1) {
    const suffix = parts.slice(1).join("").toLowerCase();
    italic = suffix.includes("italic");
    const cleanSuffix = suffix.replace("italic", "").trim();
    if (cleanSuffix && WEIGHT_MAP[cleanSuffix]) {
      weight = WEIGHT_MAP[cleanSuffix];
    }
  }

  return { family, weight, italic, filename, ext, format: FORMAT_MAP[ext] || "truetype", group, urlPath };
}

function collectFontFiles(dir, group = "local", urlPrefix = "/fonts") {
  const results = [];
  if (!existsSync(dir)) return results;

  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);

    if (stat.isDirectory()) {
      results.push(...collectFontFiles(fullPath, entry, `${urlPrefix}/${entry}`));
    } else {
      const parsed = parseFontFile(entry, group, `${urlPrefix}/${entry}`);
      if (parsed) results.push(parsed);
    }
  }

  return results;
}

function scanFonts() {
  if (!existsSync(FONTS_DIR)) {
    mkdirSync(FONTS_DIR, { recursive: true });
  }
  if (!existsSync(OUT_DIR)) {
    mkdirSync(OUT_DIR, { recursive: true });
  }

  const parsed = collectFontFiles(FONTS_DIR);

  // Группируем по font-family
  const families = new Map();
  for (const entry of parsed) {
    if (!families.has(entry.family)) {
      families.set(entry.family, { variants: [], group: entry.group });
    }
    families.get(entry.family).variants.push(entry);
  }

  // Генерируем CSS
  const cssLines = ["/* Auto-generated by scripts/scan-fonts.mjs — do not edit manually */", ""];
  for (const [family, { variants }] of families) {
    for (const v of variants) {
      cssLines.push(`@font-face {`);
      cssLines.push(`  font-family: '${family}';`);
      cssLines.push(`  src: url('${v.urlPath}') format('${v.format}');`);
      cssLines.push(`  font-weight: ${v.weight};`);
      cssLines.push(`  font-style: ${v.italic ? "italic" : "normal"};`);
      cssLines.push(`  font-display: swap;`);
      cssLines.push(`}`);
      cssLines.push(``);
    }
  }

  // Генерируем JS — собираем все уникальные группы для экспорта лейблов
  const jsEntries = [];
  const groupKeys = new Set();
  for (const [family, { variants, group }] of families) {
    const weights = variants.map((v) => v.weight).sort((a, b) => a - b);
    const hasItalic = variants.some((v) => v.italic);
    const hasBold = weights.some((w) => w >= 700);
    const regularWeight = weights.includes(400) ? 400 : weights[0];
    const boldWeight = hasBold ? weights.find((w) => w >= 700) : regularWeight;
    const key = family.toLowerCase().replace(/\s+/g, "-");
    const groupKey = group.toLowerCase().replace(/\s+/g, "-");
    groupKeys.add(groupKey);

    jsEntries.push({
      key,
      label: family,
      family: `'${family}', sans-serif`,
      group: groupKey,
      supportsBold: hasBold,
      supportsItalic: hasItalic,
      regularWeight,
      boldWeight,
      // Маппинг variantKey → URL TTF/OTF/WOFF файла. variantKey = `${weight}-${style}`,
      // где style = "normal"|"italic". Используется opentype.js-парсером
      // (src/utils/textGlyphBbox.js) для точного измерения glyph-path bbox.
      urls: variants.reduce((acc, v) => {
        const variantKey = `${v.weight}-${v.italic ? "italic" : "normal"}`;
        acc[variantKey] = v.urlPath;
        return acc;
      }, {}),
    });
  }

  // Генерируем маппинг групп (имя папки → человекочитаемый лейбл)
  const groupLabels = {};
  for (const gk of groupKeys) {
    // «local» → «Локальные», имя папки с заглавной буквы
    if (gk === "local") {
      groupLabels[gk] = "Локальные";
    } else {
      groupLabels[gk] = gk.charAt(0).toUpperCase() + gk.slice(1);
    }
  }

  const jsLines = [
    "/* Auto-generated by scripts/scan-fonts.mjs — do not edit manually */",
    "",
    `export const LOCAL_FONTS = ${JSON.stringify(jsEntries, null, 2)};`,
    "",
    `export const LOCAL_FONT_GROUP_LABELS = ${JSON.stringify(groupLabels, null, 2)};`,
    "",
  ];

  writeFileSync(join(OUT_DIR, "localFonts.css"), cssLines.join("\n"), "utf-8");
  writeFileSync(join(OUT_DIR, "localFonts.js"), jsLines.join("\n"), "utf-8");

  const count = families.size;
  const variantCount = parsed.length;
  console.log(`[scan-fonts] ${count} font famil${count === 1 ? "y" : "ies"} (${variantCount} file${variantCount === 1 ? "" : "s"}) → src/generated/localFonts.{css,js}`);

  return { families: count, files: variantCount };
}

scanFonts();

export { scanFonts };
